# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""TLS pairs from an aKMC state: units, the three-point WKB screen, and I/O."""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("pint")
pytest.importorskip("ase")
pytest.importorskip("readcon")

from click.testing import CliRunner

from rgpycrumbs.eon import tls_pairs as mod


def test_hbar_is_the_correctly_rounded_native_value():
    # h / (2 pi) with the exact SI h over sqrt(eV * dalton) Angstrom, the
    # CODATA 2022 dalton, correctly rounded by sollya at 300 bits.
    assert mod.HBAR == pytest.approx(0.06465415129579072, rel=1e-15)


def test_three_point_screen_tracks_the_exact_quartic_splitting():
    # V0 (x^2 - 1)^2 with V0 = 0.08 eV on a mass-weighted coordinate: the
    # exact gap from a 1500-point finite-difference Hamiltonian is 9.321e-5
    # eV, and the three-point cubic model through the two minima and the
    # barrier top lands within 2 percent of it.
    delta0 = mod.three_point_splitting(1.0, 1.0, 0.08, 0.0)
    assert delta0 == pytest.approx(9.321e-5, rel=0.02)
    with pytest.raises(ValueError):
        mod.three_point_splitting(1.0, 1.0, 0.01, 0.02)


def _con(path: Path, x0: float, x1: float, energy: float) -> None:
    lines = [
        "Generated by test",
        json.dumps({"con_spec_version": 2, "energy": energy}),
        "10.000000 10.000000 10.000000",
        "90.000000 90.000000 90.000000",
        "postBox_header_1",
        "postBox_header_2",
        "2",
        "1 1",
        "1.008000 15.999000",
        "H",
        "Coordinates of Component 1",
        f"{x0:.6f} 5.000000 5.000000 0 0",
        "O",
        "Coordinates of Component 2",
        f"{x1:.6f} 5.000000 5.000000 0 1",
    ]
    path.write_text("\n".join(lines) + "\n")


def _state(tmp_path: Path) -> Path:
    state = tmp_path / "states" / "0"
    proc = state / "procdata"
    proc.mkdir(parents=True)
    header = "proc #  saddle energy  prefactor  product  product energy  product prefactor  barrier  rate  repeats\n"
    # Reactant at -1.0 eV, saddle 0.08 above, product 0.002 above.
    row = (
        f"{0:7d} {-0.92:16.5f} {1e13:11.5e} {-1:9d} {-0.998:16.5f}"
        f" {1e13:17.5e} {0.08:8.5f} {1.0:12.5e} {1:7d}\n"
    )
    (state / "processtable").write_text(header + row)
    # The H atom hops 0.6 A across the periodic boundary; O stays put.
    _con(proc / "reactant_0.con", 9.8, 2.0, -1.0)
    _con(proc / "saddle_0.con", 0.1, 2.0, -0.92)
    _con(proc / "product_0.con", 0.4, 2.0, -0.998)
    return tmp_path


def test_a_state_becomes_pairs_with_minimum_image_distances(tmp_path):
    root = _state(tmp_path)
    [pair] = mod.pairs_of_state(root / "states" / "0", None)
    assert pair.path == "three_point"
    assert pair.delta.to("eV").magnitude == pytest.approx(0.002, abs=1e-9)
    assert pair.barrier.to("eV").magnitude == pytest.approx(0.08)
    # 0.6 A across the boundary, not 9.4 A, weighted by the H mass.
    assert pair.max_displacement.to("angstrom").magnitude == pytest.approx(0.6, abs=1e-6)
    assert pair.distance_mw.magnitude == pytest.approx(np.sqrt(1.008) * 0.6, rel=1e-6)
    assert pair.moved_atoms == 1
    assert pair.tls_energy.magnitude == pytest.approx(
        np.hypot(0.002, pair.delta0.magnitude)
    )


def test_the_cli_writes_the_csv_and_filters(tmp_path):
    root = _state(tmp_path)
    out = tmp_path / "tls.csv"
    result = CliRunner().invoke(mod.main, [str(root), "-o", str(out)])
    assert result.exit_code == 0, result.output
    rows = list(csv.DictReader(out.open()))
    assert len(rows) == 1 and rows[0]["path"] == "three_point"
    assert list(rows[0]) == list(mod.FIELDS)
    result = CliRunner().invoke(
        mod.main, [str(root), "-o", str(out), "--max-asymmetry", "0.001"]
    )
    assert result.exit_code == 0
    assert list(csv.DictReader(out.open())) == []
