# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""NEB profile rows come from neb.con frame metadata, not .dat columns."""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

pytest.importorskip("readcon")

from rgpycrumbs.eon.helpers import load_profile_rows


def _write_band(path: Path, frames: list[dict]) -> None:
    blocks = []
    for i, md in enumerate(frames):
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    json.dumps({"con_spec_version": 2, "neb_bead": i, **md}),
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {0.1 * i:.6f} 0 0",
                ]
            )
        )
    path.write_text("\n".join(blocks) + "\n")


def _band() -> list[dict]:
    return [
        {
            "reaction_coordinate": 0.0,
            "reaction_coordinate_mw": 0.0,
            "relative_energy": 0.0,
            "parallel_force": 0.0,
        },
        {
            "reaction_coordinate": 0.1,
            "reaction_coordinate_mw": 0.1004,
            "relative_energy": 0.25,
            "parallel_force": -0.5,
            "lowest_eigenvalue": -1.2,
        },
        {
            "reaction_coordinate": 0.2,
            "reaction_coordinate_mw": 0.2008,
            "relative_energy": 0.05,
            "parallel_force": 0.1,
        },
    ]


def test_rows_come_from_frame_metadata(tmp_path):
    con = tmp_path / "neb_path_003.con"
    _write_band(con, _band())
    rows = load_profile_rows(con)
    assert rows.shape == (5, 3)
    np.testing.assert_allclose(rows[0], [0, 1, 2])
    np.testing.assert_allclose(rows[1], [0.0, 0.1, 0.2])
    np.testing.assert_allclose(rows[2], [0.0, 0.25, 0.05])
    np.testing.assert_allclose(rows[3], [0.0, -0.5, 0.1])
    assert np.isnan(rows[4][0]) and rows[4][1] == pytest.approx(-1.2)


def test_mass_weighted_coordinate_is_read_when_asked(tmp_path):
    con = tmp_path / "neb.con"
    _write_band(con, _band())
    np.testing.assert_allclose(
        load_profile_rows(con, mass_weighted=True)[1], [0.0, 0.1004, 0.2008]
    )


def test_a_band_without_the_profile_says_what_is_missing(tmp_path):
    con = tmp_path / "neb.con"
    _write_band(con, [{"relative_energy": 0.0}] * 2)
    with pytest.raises(ValueError, match="reaction_coordinate"):
        load_profile_rows(con)
    old = [
        {k: v for k, v in md.items() if k != "reaction_coordinate_mw"} for md in _band()
    ]
    _write_band(con, old)
    with pytest.raises(ValueError, match="reaction_coordinate_mw"):
        load_profile_rows(con, mass_weighted=True)


def test_legacy_dat_is_still_read_by_column(tmp_path):
    dat = tmp_path / "neb_000.dat"
    dat.write_text("img rc energy force\n0 0.0 0.0 0.0\n1 0.1 0.2 -0.3\n")
    rows = load_profile_rows(dat)
    np.testing.assert_allclose(rows[2], [0.0, 0.2])
