# SPDX-FileCopyrightText: 2023-present Rohit Goswami <rog32@hi.is>
#
# SPDX-License-Identifier: MIT
"""con_splitter preserves CON energies through readcon read/write."""

from __future__ import annotations

import ast
from pathlib import Path

import pytest
from click.testing import CliRunner

pytest.importorskip("ase")
readcon = pytest.importorskip("readcon")

from rgpycrumbs.eon.con_splitter import (
    _is_con_path,
    _read_trajectory_frames,
    _write_con_atoms,
    con_splitter,
)


def _write_band(path: Path, frames: list[tuple[float, float]]) -> None:
    blocks = []
    for energy, z in frames:
        blocks.append(
            "\n".join(
                [
                    "Generated by test",
                    '{"con_spec_version":2,"energy":%r}' % energy,
                    "10.000000 10.000000 10.000000",
                    "90.000000 90.000000 90.000000",
                    "postBox_header_1",
                    "postBox_header_2",
                    "1",
                    "1",
                    "1.008000",
                    "H",
                    "Coordinates of Component 1",
                    f"0.000000 0.000000 {z:.6f} 0 0",
                ]
            )
        )
    path.write_text("\n".join(blocks) + "\n")


def test_is_con_path_helper():
    assert _is_con_path(Path("neb.con"))
    assert _is_con_path(Path("x.convel"))
    assert not _is_con_path(Path("neb.traj"))


def test_write_con_atoms_roundtrip_energy(tmp_path: Path):
    from ase import Atoms

    atoms = Atoms("H", positions=[[0, 0, 0.25]], cell=[10, 10, 10], pbc=True)
    dest = tmp_path / "one.con"
    _write_con_atoms(dest, atoms, energy=-7.5)
    frame = readcon.read_con(str(dest))[0]
    assert frame.energy == pytest.approx(-7.5)
    assert frame.to_ase().get_positions()[0, 2] == pytest.approx(0.25)


def test_read_trajectory_frames_attaches_energy_info(tmp_path: Path):
    band = tmp_path / "neb.con"
    _write_band(band, [(0.5, 0.0), (1.5, 0.5)])
    atoms_list, con_frames = _read_trajectory_frames(band)
    assert con_frames is not None
    assert len(atoms_list) == 2 == len(con_frames)
    assert atoms_list[0].info["energy"] == pytest.approx(0.5)
    assert con_frames[1].energy == pytest.approx(1.5)


def test_split_con_input_preserves_energies(tmp_path: Path):
    band = tmp_path / "neb.con"
    _write_band(band, [(0.0, 0.0), (1.0, 0.5), (2.0, 1.0), (3.0, 1.5)])
    out = tmp_path / "split"
    runner = CliRunner()
    result = runner.invoke(
        con_splitter,
        [
            str(band),
            "--images-per-path",
            "2",
            "--output-dir",
            str(out),
            "--path-index",
            "1",
            "--align-type",
            "none",
        ],
    )
    assert result.exit_code == 0, result.output
    cons = sorted(out.glob("ipath_*.con"))
    assert len(cons) == 2
    energies = [readcon.read_con(str(p))[0].energy for p in cons]
    assert energies == pytest.approx([2.0, 3.0])
    for p in cons:
        assert readcon.read_con(str(p))[0].to_ase().get_chemical_symbols() == ["H"]


def test_con_splitter_source_has_no_asewrite():
    src = Path(con_splitter.callback.__code__.co_filename)
    tree = ast.parse(src.read_text())
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module == "ase.io":
            assert all(alias.name != "write" for alias in node.names)
    text = src.read_text()
    assert "readcon>=0.7.0" in text
    assert "asewrite" not in text
